/**
 * Curated pt-BR marker lexicon for real-estate copy. Every `pattern` is a regex source that the
 * scanner compiles with the `giu` flags inside accent-aware boundaries
 * `(?<![\p{L}\p{N}])` … `(?![\p{L}\p{N}])`. Never use `\b` or `\w` here: with the `u` flag they
 * do not know accented letters ("ç", "ã", "ó"). Use `\p{L}` instead.
 *
 * Severity: `block` fails the gate; `warn` is reported and turned into an editor hint.
 * Forms shared by both norms under AO90 (ação, ótimo, direto, atual, ideia, assembleia…) and shared
 * vocabulary (condomínio, garagem, piscina, elevador, varanda, terraço, quintal, churrasqueira,
 * banheira, imóvel) must never appear here; `test/lexicon.test.ts` guards a precision list.
 */
import { GRAMMAR_RULES } from "../grammarPatterns";

export interface Marker {
  id: string;
  pattern: string;
  severity: "block" | "warn";
  suggestion: string;
  category: "lexical" | "spelling" | "grammar" | "register";
  note?: string;
  /** Strings the marker must match; every entry is unit-tested against its own examples. */
  examples: string[];
}

const L = "\\p{L}";

const LEXICAL: Marker[] = [
  // ---- rooms, floors and parts of the building --------------------------------------------
  {
    id: "lex.terreo",
    pattern: "térreo|andar\\s+térreo|piso\\s+térreo",
    severity: "block",
    suggestion: "rés-do-chão",
    category: "lexical",
    note: "«moradia térrea» is fine in pt-PT; only the masculine floor sense is Brazilian.",
    examples: ["loja no térreo", "apartamento no andar térreo"],
  },
  {
    id: "lex.banheiro",
    pattern: "banheiros?",
    severity: "block",
    suggestion: "casa de banho",
    category: "lexical",
    examples: ["dois banheiros completos", "banheiro com banheira"],
  },
  {
    id: "lex.lavabo",
    pattern: "lavabos?",
    severity: "block",
    suggestion: "casa de banho de serviço",
    category: "lexical",
    examples: ["sala com lavabo"],
  },
  {
    id: "lex.vaso_sanitario",
    pattern: "vasos?\\s+sanitários?",
    severity: "block",
    suggestion: "sanita",
    category: "lexical",
    examples: ["vaso sanitário suspenso"],
  },
  {
    id: "lex.pia",
    pattern: "pias?",
    severity: "block",
    suggestion: "lava-loiça / lavatório",
    category: "lexical",
    examples: ["pia de granito", "pia do banheiro"],
  },
  {
    id: "lex.ducha",
    pattern: "duchas?",
    severity: "block",
    suggestion: "duche",
    category: "lexical",
    examples: ["ducha com aquecedor"],
  },
  {
    id: "lex.bide",
    pattern: "bidês?",
    severity: "block",
    suggestion: "bidé",
    category: "spelling",
    examples: ["sanita e bidê"],
  },
  {
    id: "lex.box",
    pattern: "box(?:es)?(?:\\s+de\\s+vidro)?",
    severity: "warn",
    suggestion: "resguardo de duche / cabine de duche",
    category: "lexical",
    examples: ["banheiro com box de vidro"],
  },
  {
    id: "lex.dormitorio",
    pattern: "dormitórios?",
    severity: "block",
    suggestion: "quarto",
    category: "lexical",
    examples: ["3 dormitórios", "dormitório com armário"],
  },
  {
    id: "lex.comodo",
    pattern: "cômodos?",
    severity: "block",
    suggestion: "divisão / divisões",
    category: "lexical",
    examples: ["seis cômodos amplos"],
  },
  {
    id: "lex.ambientes",
    pattern: "ambientes",
    severity: "warn",
    suggestion: "divisões",
    category: "lexical",
    note: "Only the plural noun for rooms is Brazilian; «ambiente» (atmosphere) is shared.",
    examples: ["apartamento de 2 ambientes"],
  },
  {
    id: "lex.suite",
    pattern: "suítes?",
    severity: "warn",
    suggestion: "suite",
    category: "lexical",
    examples: ["quarto com suíte"],
  },
  {
    id: "lex.cozinha_americana",
    pattern: "cozinha\\s+americana",
    severity: "warn",
    suggestion: "cozinha em open space",
    category: "lexical",
    examples: ["A cozinha americana é planejada"],
  },
  {
    id: "lex.closet",
    pattern: "closets?",
    severity: "warn",
    suggestion: "roupeiro / closet (zona de vestir)",
    category: "lexical",
    examples: ["suíte com closet"],
  },
  {
    id: "lex.guarda_roupa",
    pattern: "guarda-roupas?",
    severity: "warn",
    suggestion: "roupeiro",
    category: "lexical",
    examples: ["guarda-roupa embutido"],
  },
  {
    id: "lex.lavanderia",
    pattern: "lavanderias?",
    severity: "block",
    suggestion: "lavandaria",
    category: "lexical",
    examples: ["lavanderia com tanque"],
  },
  {
    id: "lex.area_de_servico",
    pattern: "áreas?\\s+de\\s+serviço",
    severity: "block",
    suggestion: "lavandaria",
    category: "lexical",
    examples: ["cozinha com área de serviço"],
  },
  {
    id: "lex.dependencia_empregada",
    pattern: "dependências?\\s+(?:de|para)\\s+empregad[ao]s?",
    severity: "block",
    suggestion: "quarto de serviço",
    category: "lexical",
    examples: ["dependência de empregada completa"],
  },
  {
    id: "lex.sacada",
    pattern: "sacadas?",
    severity: "block",
    suggestion: "varanda",
    category: "lexical",
    examples: ["sacada com vista", "duas sacadas"],
  },
  {
    id: "lex.cobertura",
    pattern: "coberturas?(?:\\s+duplex)?",
    severity: "warn",
    suggestion: "penthouse / último piso",
    category: "lexical",
    note: "«cobertura» also means roofing or network coverage in pt-PT.",
    examples: ["cobertura duplex com piscina"],
  },
  {
    id: "lex.porao",
    pattern: "porão|porões",
    severity: "block",
    suggestion: "cave",
    category: "lexical",
    examples: ["porão para armazenamento"],
  },
  {
    id: "lex.subsolo",
    pattern: "subsolos?",
    severity: "block",
    suggestion: "cave / piso -1",
    category: "lexical",
    examples: ["garagem no subsolo"],
  },
  {
    id: "lex.deposito",
    pattern: "depósitos?",
    severity: "warn",
    suggestion: "arrecadação",
    category: "lexical",
    note: "«depósito» is also a bank deposit or a water tank in pt-PT.",
    examples: ["vaga de garagem e depósito"],
  },
  {
    id: "lex.edicula",
    pattern: "edículas?",
    severity: "block",
    suggestion: "anexo",
    category: "lexical",
    examples: ["quintal com edícula"],
  },
  {
    id: "lex.jirau",
    pattern: "jiraus?",
    severity: "block",
    suggestion: "mezanino",
    category: "lexical",
    examples: ["loft com jirau"],
  },
  {
    id: "lex.puxadinho",
    pattern: "puxadinhos?",
    severity: "block",
    suggestion: "anexo",
    category: "register",
    examples: ["casa com puxadinho nos fundos"],
  },
  {
    id: "lex.forro",
    pattern: "forros?(?:\\s+de\\s+gesso)?",
    severity: "block",
    suggestion: "teto falso",
    category: "lexical",
    note: "In pt-PT «forro» is the lining of a garment.",
    examples: ["forro de gesso com iluminação"],
  },
  {
    id: "lex.esquadrias",
    pattern: "esquadrias?",
    severity: "block",
    suggestion: "caixilharia",
    category: "lexical",
    examples: ["esquadrias com vidros duplos", "esquadria de alumínio"],
  },
  {
    id: "lex.piso_laminado",
    pattern: "pisos?\\s+laminados?",
    severity: "block",
    suggestion: "pavimento flutuante",
    category: "lexical",
    examples: ["quartos com piso laminado"],
  },
  {
    id: "lex.porcelanato",
    pattern: "porcelanatos?",
    severity: "block",
    suggestion: "grés porcelânico",
    category: "lexical",
    examples: ["sala em porcelanato"],
  },
  {
    id: "lex.assoalho",
    pattern: "assoalhos?",
    severity: "block",
    suggestion: "soalho",
    category: "lexical",
    examples: ["assoalho de madeira restaurado"],
  },
  {
    id: "lex.rejunte",
    pattern: "rejuntes?",
    severity: "block",
    suggestion: "juntas / betume",
    category: "lexical",
    examples: ["rejunte novo nos azulejos"],
  },
  {
    id: "lex.gas_encanado",
    pattern: "gás\\s+encanado",
    severity: "block",
    suggestion: "gás canalizado",
    category: "lexical",
    examples: ["cozinha com gás encanado"],
  },
  {
    id: "lex.encanamento",
    pattern: "encanamentos?|encanador(?:es|a|as)?",
    severity: "block",
    suggestion: "canalização / canalizador",
    category: "lexical",
    examples: ["encanamento novo", "trabalho de encanador"],
  },
  {
    id: "lex.hidraulica",
    pattern: "(?:parte|instalação|instalações|rede)\\s+hidráulicas?",
    severity: "warn",
    suggestion: "canalização",
    category: "lexical",
    examples: ["parte hidráulica revisada"],
  },
  {
    id: "lex.aquecedor_a_gas",
    pattern: "aquecedor(?:es)?\\s+a\\s+gás",
    severity: "block",
    suggestion: "esquentador",
    category: "lexical",
    examples: ["água quente por aquecedor a gás"],
  },
  {
    id: "lex.boiler",
    pattern: "boilers?",
    severity: "block",
    suggestion: "termoacumulador",
    category: "lexical",
    examples: ["boiler elétrico de 200 litros"],
  },
  {
    id: "lex.botijao",
    pattern: "botij(?:ão|ões)",
    severity: "block",
    suggestion: "botija / garrafa de gás",
    category: "lexical",
    examples: ["fogão a botijão"],
  },
  {
    id: "lex.concreto",
    pattern: "concreto\\s+armado|(?:de|em)\\s+concreto",
    severity: "block",
    suggestion: "betão / betão armado",
    category: "lexical",
    note: "The adjective «concreto» (concrete, tangible) is shared; only the material is flagged.",
    examples: ["estrutura em concreto armado", "laje de concreto"],
  },
  {
    id: "lex.marcenaria",
    pattern: "marcenarias?",
    severity: "block",
    suggestion: "carpintaria",
    category: "lexical",
    examples: ["marcenaria sob medida"],
  },
  {
    id: "lex.sob_medida",
    pattern: "sob\\s+medida",
    severity: "block",
    suggestion: "por medida / à medida",
    category: "lexical",
    examples: ["móveis sob medida"],
  },
  {
    id: "lex.planejado",
    pattern: "planejad[oa]s?",
    severity: "block",
    suggestion: "por medida",
    category: "lexical",
    examples: ["armários planejados", "cozinha planejada"],
  },
  {
    id: "lex.armarios_planejados",
    pattern: "armários\\s+planejados",
    severity: "block",
    suggestion: "roupeiros por medida",
    category: "lexical",
    examples: ["quartos com armários planejados"],
  },
  {
    id: "lex.persiana",
    pattern: "persianas?",
    severity: "warn",
    suggestion: "estores",
    category: "lexical",
    examples: ["persianas em todos os quartos"],
  },
  {
    id: "lex.blindex",
    pattern: "blindex",
    severity: "warn",
    suggestion: "vidro temperado",
    category: "lexical",
    examples: ["porta de blindex"],
  },
  {
    id: "lex.tela_mosquiteira",
    pattern: "telas?\\s+(?:mosquiteiras?|de\\s+proteção)",
    severity: "block",
    suggestion: "rede mosquiteira / rede de proteção",
    category: "lexical",
    examples: ["janelas com tela mosquiteira"],
  },
  {
    id: "lex.d_agua",
    pattern: "d['’]água",
    severity: "block",
    suggestion: "de água",
    category: "lexical",
    examples: ["espelho d'água no jardim", "caixa d’água"],
  },
  {
    id: "lex.ventilador_de_teto",
    pattern: "ventilador(?:es)?\\s+de\\s+teto",
    severity: "warn",
    suggestion: "ventoinha de teto",
    category: "lexical",
    examples: ["quartos com ventilador de teto"],
  },
  {
    id: "lex.olho_magico",
    pattern: "olho\\s+mágico",
    severity: "block",
    suggestion: "óculo",
    category: "lexical",
    examples: ["porta blindada com olho mágico"],
  },
  {
    id: "lex.interfone",
    pattern: "interfones?",
    severity: "block",
    suggestion: "intercomunicador",
    category: "lexical",
    examples: ["portaria com interfone"],
  },
  {
    id: "lex.porteiro_eletronico",
    pattern: "porteiros?\\s+eletr[ôo]nicos?",
    severity: "block",
    suggestion: "vídeo-porteiro",
    category: "lexical",
    examples: ["porteiro eletrônico na entrada"],
  },
  {
    id: "lex.zelador",
    pattern: "zelador(?:es|a|as)?",
    severity: "block",
    suggestion: "porteiro",
    category: "lexical",
    examples: ["prédio com zelador"],
  },
  {
    id: "lex.sindico",
    pattern: "síndic[oa]s?",
    severity: "block",
    suggestion: "administrador do condomínio",
    category: "lexical",
    examples: ["fale com o síndico"],
  },
  {
    id: "lex.faxineira",
    pattern: "faxin(?:a|as|eir[ao]s?)",
    severity: "block",
    suggestion: "limpeza / empregada de limpeza",
    category: "lexical",
    examples: ["faxineira duas vezes por semana"],
  },
  {
    id: "lex.camera",
    pattern: "câmeras?",
    severity: "block",
    suggestion: "câmara",
    category: "spelling",
    examples: ["câmeras de segurança"],
  },
  {
    id: "lex.monitoramento",
    pattern: "monitoramentos?|monitorad[oa]s?",
    severity: "block",
    suggestion: "monitorização / monitorizado",
    category: "spelling",
    examples: ["monitoramento 24 horas", "condomínio monitorado"],
  },
  {
    id: "lex.controle",
    pattern: "controles?\\s+(?:de|remotos?)|(?:com|sem|o|um|do|no)\\s+controles?",
    severity: "block",
    suggestion: "controlo",
    category: "spelling",
    examples: ["controle de acesso", "controle remoto"],
  },
  // ---- condition and works -------------------------------------------------------------------
  {
    id: "lex.reformado",
    pattern: "reformad[oa]s?",
    severity: "block",
    suggestion: "remodelado",
    category: "lexical",
    note: "In pt-PT «reformado» means retired (a pensioner).",
    examples: ["totalmente reformado em 2021", "cozinha reformada"],
  },
  {
    id: "lex.reforma",
    pattern: "reformas?",
    severity: "warn",
    suggestion: "remodelação / obras",
    category: "lexical",
    note: "In pt-PT «reforma» is retirement or a pension.",
    examples: ["passou por reforma completa"],
  },
  {
    id: "lex.mobiliado",
    pattern: "(?:semi-?)?mobiliad[oa]s?",
    severity: "block",
    suggestion: "mobilado",
    category: "lexical",
    examples: ["apartamento mobiliado", "semimobiliado"],
  },
  {
    id: "lex.pronto_para_morar",
    pattern: "pront[oa]s?\\s+para\\s+morar",
    severity: "block",
    suggestion: "pronto a habitar",
    category: "lexical",
    examples: ["está pronto para morar"],
  },
  {
    id: "lex.seminovo",
    pattern: "semi-?nov[oa]s?",
    severity: "block",
    suggestion: "como novo",
    category: "lexical",
    examples: ["apartamento seminovo"],
  },
  {
    id: "lex.na_planta",
    pattern: "(?:comprar|compra|comprado|adquirir|vendido|venda|imóvel|apartamento)\\s+na\\s+planta",
    severity: "warn",
    suggestion: "em planta",
    category: "lexical",
    examples: ["comprar na planta"],
  },
  {
    id: "lex.planta_baixa",
    pattern: "plantas?\\s+baixas?",
    severity: "warn",
    suggestion: "planta",
    category: "lexical",
    examples: ["veja a planta baixa"],
  },
  {
    id: "lex.apartamento_decorado",
    pattern: "apartamentos?\\s+decorados?",
    severity: "warn",
    suggestion: "apartamento modelo",
    category: "lexical",
    examples: ["visite o apartamento decorado"],
  },
  {
    id: "lex.incorporadora",
    pattern: "incorporadoras?",
    severity: "block",
    suggestion: "promotora imobiliária",
    category: "lexical",
    examples: ["lançamento da incorporadora"],
  },
  // ---- parking, garage and the building's amenities ----------------------------------------
  {
    id: "lex.vaga_de_garagem",
    pattern:
      "(?:\\d+|uma|duas|três|quatro|sem)\\s+vagas?(?:\\s+(?:de|para)\\s+(?:garagem|estacionamento|carros?|visitantes?|motos?))?|vagas?\\s+(?:de|para)\\s+(?:garagem|estacionamento|carros?|visitantes?|motos?)",
    severity: "block",
    suggestion: "lugar de garagem / lugar de estacionamento",
    category: "lexical",
    examples: ["vaga de garagem coberta", "2 vagas de estacionamento", "duas vagas"],
  },
  {
    id: "lex.vaga",
    pattern: "vagas?",
    severity: "warn",
    suggestion: "lugar de garagem",
    category: "lexical",
    note: "Bare «vaga» is a job vacancy in pt-PT; counted or qualified forms are blocked by lex.vaga_de_garagem.",
    examples: ["com sacada e vaga"],
  },
  {
    id: "lex.academia",
    pattern: "academias?(?!\\s+(?:das\\s+ciências|de\\s+música|de\\s+artes|de\\s+dança|militar))",
    severity: "block",
    suggestion: "ginásio",
    category: "lexical",
    examples: ["condomínio com academia", "academia de ginástica"],
  },
  {
    id: "lex.espaco_fitness",
    pattern: "espaços?\\s+fitness",
    severity: "warn",
    suggestion: "ginásio",
    category: "lexical",
    examples: ["espaço fitness equipado"],
  },
  {
    id: "lex.shopping",
    pattern: "shoppings?(?:\\s+centers?)?",
    severity: "block",
    suggestion: "centro comercial",
    category: "lexical",
    examples: ["perto do shopping", "shopping center a 5 minutos"],
  },
  {
    id: "lex.playground",
    pattern: "playgrounds?",
    severity: "block",
    suggestion: "parque infantil",
    category: "lexical",
    examples: ["playground para as crianças"],
  },
  {
    id: "lex.brinquedoteca",
    pattern: "brinquedotecas?",
    severity: "block",
    suggestion: "sala infantil",
    category: "lexical",
    examples: ["brinquedoteca e salão de festas"],
  },
  {
    id: "lex.espaco_kids",
    pattern: "espaços?\\s+kids",
    severity: "block",
    suggestion: "zona infantil",
    category: "lexical",
    examples: ["espaço kids coberto"],
  },
  {
    id: "lex.salao_de_festas",
    pattern: "sal(?:ão|ões)\\s+de\\s+festas",
    severity: "warn",
    suggestion: "sala de convívio / salão de eventos",
    category: "lexical",
    examples: ["salão de festas equipado"],
  },
  {
    id: "lex.salao_de_jogos",
    pattern: "sal(?:ão|ões)\\s+de\\s+jogos",
    severity: "warn",
    suggestion: "sala de jogos",
    category: "lexical",
    examples: ["salão de jogos para adolescentes"],
  },
  {
    id: "lex.bicicletario",
    pattern: "bicicletários?",
    severity: "block",
    suggestion: "parque de bicicletas",
    category: "lexical",
    examples: ["bicicletário coberto"],
  },
  {
    id: "lex.quadra",
    pattern: "quadras?",
    severity: "warn",
    suggestion: "quarteirão (distância) / campo (desporto)",
    category: "lexical",
    examples: ["a duas quadras da praia", "quadra de tênis"],
  },
  {
    id: "lex.poliesportiva",
    pattern: "poli-?esportiv[oa]s?",
    severity: "block",
    suggestion: "polidesportivo",
    category: "spelling",
    examples: ["quadra poliesportiva"],
  },
  {
    id: "lex.lazer_completo",
    pattern: "lazer\\s+complet[oa]",
    severity: "block",
    suggestion: "comodidades",
    category: "lexical",
    examples: ["condomínio com lazer completo"],
  },
  {
    id: "lex.area_de_lazer",
    pattern: "áreas?\\s+de\\s+lazer",
    severity: "warn",
    suggestion: "zona de lazer / comodidades",
    category: "lexical",
    examples: ["ampla área de lazer"],
  },
  {
    id: "lex.infraestrutura_completa",
    pattern: "infra-?estrutura\\s+completa",
    severity: "warn",
    suggestion: "todas as comodidades",
    category: "lexical",
    examples: ["prédio com infraestrutura completa"],
  },
  {
    id: "lex.pet_place",
    pattern: "pet\\s+places?",
    severity: "block",
    suggestion: "área para animais",
    category: "lexical",
    examples: ["condomínio com pet place"],
  },
  {
    id: "lex.pet_friendly",
    pattern: "pet\\s+friendly|aceita\\s+pets?",
    severity: "warn",
    suggestion: "aceita animais de estimação",
    category: "lexical",
    examples: ["prédio pet friendly", "aceita pet"],
  },
  {
    id: "lex.area_gourmet",
    pattern: "(?:áreas?|varandas?|espaços?|sacadas?|terraços?)\\s+gourmet",
    severity: "block",
    suggestion: "zona de refeições exterior",
    category: "lexical",
    examples: ["área gourmet com churrasqueira", "varanda gourmet", "espaço gourmet"],
  },
  {
    id: "lex.alto_padrao",
    pattern: "alt[oa]\\s+padrão|altíssimo\\s+padrão",
    severity: "block",
    suggestion: "de luxo / de qualidade superior",
    category: "lexical",
    examples: ["acabamentos de alto padrão", "apartamento de altíssimo padrão"],
  },
  {
    id: "lex.medio_padrao",
    pattern: "médio\\s+padrão",
    severity: "block",
    suggestion: "de gama média",
    category: "lexical",
    examples: ["imóvel de médio padrão"],
  },
  {
    id: "lex.bairro_nobre",
    pattern: "bairros?\\s+nobres?",
    severity: "block",
    suggestion: "zona nobre",
    category: "lexical",
    examples: ["um bairro nobre e consolidado"],
  },
  // ---- property types ----------------------------------------------------------------------
  {
    id: "lex.sobrado",
    pattern: "sobrados?",
    severity: "block",
    suggestion: "moradia de dois pisos",
    category: "lexical",
    examples: ["sobrado com 4 quartos"],
  },
  {
    id: "lex.kitnet",
    pattern: "kitnets?|kitinetes?|quitinetes?",
    severity: "block",
    suggestion: "T0 / estúdio",
    category: "lexical",
    examples: ["kitnet perto da universidade", "quitinete mobiliada"],
  },
  {
    id: "lex.conjugado",
    pattern: "(?:apartamentos?|quartos?)\\s+conjugados?",
    severity: "warn",
    suggestion: "T0 / estúdio",
    category: "lexical",
    examples: ["apartamento conjugado"],
  },
  {
    id: "lex.ape",
    pattern: "apês?",
    severity: "block",
    suggestion: "apartamento",
    category: "register",
    examples: ["apê novinho"],
  },
  {
    id: "lex.flat",
    pattern: "flats?",
    severity: "warn",
    suggestion: "apartamento / estúdio com serviços",
    category: "lexical",
    examples: ["flat com serviço de hotel"],
  },
  {
    id: "lex.chacara",
    pattern: "chácaras?",
    severity: "block",
    suggestion: "quinta",
    category: "lexical",
    examples: ["chácara com pomar"],
  },
  {
    id: "lex.fazenda",
    pattern: "fazendas?",
    severity: "block",
    suggestion: "herdade / quinta",
    category: "lexical",
    examples: ["fazenda de 20 hectares"],
  },
  // ---- money, law and paperwork ------------------------------------------------------------
  {
    id: "lex.aluguel",
    pattern: "alugu[eé]is|aluguel",
    severity: "block",
    suggestion: "arrendamento / renda / aluguer",
    category: "lexical",
    examples: ["aluguel de 1.500 por mês", "aluguéis acessíveis"],
  },
  {
    id: "lex.locacao",
    pattern: "locaç(?:ão|ões)",
    severity: "block",
    suggestion: "arrendamento",
    category: "lexical",
    examples: ["disponível para locação"],
  },
  {
    id: "lex.locatario",
    pattern: "locatári[oa]s?",
    severity: "block",
    suggestion: "arrendatário / inquilino",
    category: "lexical",
    examples: ["responsabilidade do locatário"],
  },
  {
    id: "lex.locador",
    pattern: "locador(?:es|a|as)?",
    severity: "block",
    suggestion: "senhorio",
    category: "lexical",
    examples: ["o locador exige fiador"],
  },
  {
    id: "lex.real_brasileiro",
    pattern: "R\\$\\s*\\d{1,3}(?:[.\\s]\\d{3})*(?:,\\d+)?|R\\$",
    severity: "block",
    suggestion: "€",
    category: "lexical",
    examples: ["R$ 350.000", "valor em R$"],
  },
  {
    id: "lex.reais",
    pattern: "(?:mil|milh(?:ão|ões)|\\d+)\\s+reais",
    severity: "block",
    suggestion: "euros",
    category: "lexical",
    examples: ["350 mil reais"],
  },
  {
    id: "lex.iptu",
    pattern: "IPTU",
    severity: "block",
    suggestion: "IMI",
    category: "lexical",
    examples: ["IPTU incluído"],
  },
  {
    id: "lex.itbi",
    pattern: "ITBI",
    severity: "block",
    suggestion: "IMT",
    category: "lexical",
    examples: ["ITBI por conta do comprador"],
  },
  {
    id: "lex.habite_se",
    pattern: "habite-se",
    severity: "block",
    suggestion: "licença de utilização",
    category: "lexical",
    examples: ["com habite-se emitido"],
  },
  {
    id: "lex.matricula_do_imovel",
    pattern: "matrículas?\\s+(?:do|de|dos)\\s+im[óo]ve(?:l|is)",
    severity: "block",
    suggestion: "caderneta predial",
    category: "lexical",
    examples: ["matrícula do imóvel atualizada"],
  },
  {
    id: "lex.cartorio",
    pattern: "cartórios?(?!\\s+notaria(?:l|is))",
    severity: "block",
    suggestion: "conservatória do registo predial",
    category: "lexical",
    note: "«cartório notarial» exists in pt-PT and is not flagged.",
    examples: ["registrado em cartório"],
  },
  {
    id: "lex.tabeliao",
    pattern: "tabeli(?:ão|ães|oa|oas)",
    severity: "block",
    suggestion: "notário",
    category: "lexical",
    examples: ["assinatura perante tabelião"],
  },
  {
    id: "lex.creci",
    pattern: "CRECI",
    severity: "block",
    suggestion: "licença AMI",
    category: "lexical",
    examples: ["corretor com CRECI ativo"],
  },
  {
    id: "lex.corretor",
    pattern: "corretor(?:es|a|as)?(?:\\s+de\\s+imóveis|\\s+imobiliári[oa]s?)?",
    severity: "warn",
    suggestion: "consultor imobiliário / mediador",
    category: "lexical",
    examples: ["fale com nosso corretor de imóveis"],
  },
  {
    id: "lex.fgts",
    pattern: "FGTS",
    severity: "block",
    suggestion: "(não aplicável em Portugal)",
    category: "lexical",
    examples: ["aceita FGTS"],
  },
  {
    id: "lex.minha_casa_minha_vida",
    pattern: "minha\\s+casa\\s+minha\\s+vida",
    severity: "block",
    suggestion: "(programa não aplicável em Portugal)",
    category: "lexical",
    examples: ["financiável pelo Minha Casa Minha Vida"],
  },
  {
    id: "lex.cep",
    pattern: "CEP",
    severity: "block",
    suggestion: "código postal",
    category: "lexical",
    examples: ["CEP 01310-100"],
  },
  {
    id: "lex.cpf",
    pattern: "CPF|CNPJ",
    severity: "block",
    suggestion: "NIF",
    category: "lexical",
    examples: ["apresentar CPF"],
  },
  {
    id: "lex.quitado",
    pattern: "quitad[oa]s?",
    severity: "block",
    suggestion: "liquidado / totalmente pago",
    category: "lexical",
    examples: ["imóvel quitado"],
  },
  {
    id: "lex.parcelas",
    pattern: "parcelas?\\s+(?:mensais|do\\s+financiamento|fixas)|em\\s+\\d+\\s+parcelas",
    severity: "warn",
    suggestion: "prestações",
    category: "lexical",
    examples: ["parcelas mensais de 1.200", "em 60 parcelas"],
  },
  {
    id: "lex.reajuste",
    pattern: "reajustes?",
    severity: "warn",
    suggestion: "atualização (da renda)",
    category: "lexical",
    examples: ["reajuste anual"],
  },
  {
    id: "lex.custo_beneficio",
    pattern: "custo[- ]benefício",
    severity: "warn",
    suggestion: "relação qualidade/preço",
    category: "lexical",
    examples: ["ótimo custo-benefício"],
  },
  {
    id: "lex.metragem",
    pattern: "metrage(?:m|ns)",
    severity: "block",
    suggestion: "área",
    category: "lexical",
    examples: ["metragem generosa"],
  },
  {
    id: "lex.area_total",
    pattern: "áreas?\\s+tota(?:l|is)",
    severity: "warn",
    suggestion: "área bruta",
    category: "lexical",
    examples: ["132 m² de área total"],
  },
  {
    id: "lex.area_privativa",
    pattern: "áreas?\\s+privativas?",
    severity: "warn",
    suggestion: "área útil",
    category: "lexical",
    examples: ["80 m² de área privativa"],
  },
  {
    id: "lex.area_construida",
    pattern: "áreas?\\s+construídas?",
    severity: "warn",
    suggestion: "área bruta de construção",
    category: "lexical",
    examples: ["200 m² de área construída"],
  },
  // ---- neighbourhood, transport and services ----------------------------------------------
  {
    id: "lex.onibus",
    pattern: "[ôo]nibus",
    severity: "block",
    suggestion: "autocarro",
    category: "lexical",
    examples: ["linhas de ônibus", "onibus na porta"],
  },
  {
    id: "lex.ponto_de_onibus",
    pattern: "pontos?\\s+de\\s+[ôo]nibus",
    severity: "block",
    suggestion: "paragem de autocarro",
    category: "lexical",
    examples: ["ponto de ônibus em frente"],
  },
  {
    id: "lex.metro",
    pattern: "metrô",
    severity: "block",
    suggestion: "metro",
    category: "spelling",
    examples: ["a 5 minutos do metrô"],
  },
  {
    id: "lex.trem",
    pattern: "tre(?:m|ns)",
    severity: "block",
    suggestion: "comboio",
    category: "lexical",
    examples: ["estação de trem próxima"],
  },
  {
    id: "lex.bonde",
    pattern: "bondes?",
    severity: "block",
    suggestion: "elétrico",
    category: "lexical",
    examples: ["o bonde 28 passa na rua"],
  },
  {
    id: "lex.rodovia",
    pattern: "rodovias?",
    severity: "block",
    suggestion: "autoestrada",
    category: "lexical",
    examples: ["acesso rápido à rodovia"],
  },
  {
    id: "lex.pedagio",
    pattern: "pedágios?",
    severity: "block",
    suggestion: "portagem",
    category: "lexical",
    examples: ["sem pedágio até o centro"],
  },
  {
    id: "lex.rodoviaria",
    pattern: "rodoviárias?",
    severity: "warn",
    suggestion: "estação de camionagem / terminal rodoviário",
    category: "lexical",
    examples: ["perto da rodoviária"],
  },
  {
    id: "lex.calcadao",
    pattern: "calçad(?:ão|ões)",
    severity: "block",
    suggestion: "passeio marítimo / marginal",
    category: "lexical",
    examples: ["a 2 quadras do calçadão"],
  },
  {
    id: "lex.pedestre",
    pattern: "pedestres?",
    severity: "block",
    suggestion: "peão / peões",
    category: "lexical",
    examples: ["rua exclusiva para pedestres"],
  },
  {
    id: "lex.faixa_de_pedestres",
    pattern: "faixas?\\s+de\\s+pedestres?",
    severity: "block",
    suggestion: "passadeira",
    category: "lexical",
    examples: ["faixa de pedestres em frente"],
  },
  {
    id: "lex.carona",
    pattern: "caronas?",
    severity: "block",
    suggestion: "boleia",
    category: "lexical",
    examples: ["fácil pegar carona"],
  },
  {
    id: "lex.caminhando",
    pattern: "caminhando",
    severity: "block",
    suggestion: "a pé",
    category: "lexical",
    examples: ["a poucos minutos caminhando"],
  },
  {
    id: "lex.celular",
    pattern: "celular(?:es)?",
    severity: "block",
    suggestion: "telemóvel",
    category: "lexical",
    examples: ["ligue do seu celular"],
  },
  {
    id: "lex.posto_de_saude",
    pattern: "postos?\\s+de\\s+saúde",
    severity: "block",
    suggestion: "centro de saúde",
    category: "lexical",
    examples: ["posto de saúde a 200 m"],
  },
  {
    id: "lex.pronto_socorro",
    pattern: "pronto[- ]socorro",
    severity: "block",
    suggestion: "serviço de urgência",
    category: "lexical",
    examples: ["hospital com pronto-socorro"],
  },
  {
    id: "lex.drogaria",
    pattern: "drogarias?",
    severity: "block",
    suggestion: "farmácia",
    category: "lexical",
    examples: ["drogaria na esquina"],
  },
  {
    id: "lex.delegacia",
    pattern: "delegacias?",
    severity: "block",
    suggestion: "esquadra",
    category: "lexical",
    examples: ["delegacia a 300 metros"],
  },
  {
    id: "lex.prefeitura",
    pattern: "prefeituras?",
    severity: "block",
    suggestion: "câmara municipal",
    category: "lexical",
    examples: ["perto da prefeitura"],
  },
  {
    id: "lex.prefeito",
    pattern: "prefeit[oa]s?",
    severity: "block",
    suggestion: "presidente da câmara",
    category: "lexical",
    examples: ["obra da prefeita"],
  },
  {
    id: "lex.coleta",
    pattern: "coletas?(?:\\s+seletiva)?",
    severity: "block",
    suggestion: "recolha",
    category: "lexical",
    examples: ["coleta seletiva de lixo"],
  },
  {
    id: "lex.ensino_fundamental",
    pattern: "ensino\\s+fundamental",
    severity: "block",
    suggestion: "ensino básico",
    category: "lexical",
    examples: ["escolas de ensino fundamental"],
  },
  {
    id: "lex.ensino_medio",
    pattern: "ensino\\s+médio",
    severity: "block",
    suggestion: "ensino secundário",
    category: "lexical",
    examples: ["colégio de ensino médio"],
  },
  {
    id: "lex.posto_de_gasolina",
    pattern: "postos?\\s+de\\s+gasolina",
    severity: "warn",
    suggestion: "posto de combustível / bomba de gasolina",
    category: "lexical",
    examples: ["posto de gasolina na avenida"],
  },
  {
    id: "lex.lanchonete",
    pattern: "lanchonetes?",
    severity: "block",
    suggestion: "café / snack-bar",
    category: "lexical",
    examples: ["lanchonete no térreo"],
  },
  {
    id: "lex.sorveteria",
    pattern: "sorveterias?",
    severity: "block",
    suggestion: "gelataria",
    category: "lexical",
    examples: ["sorveteria famosa"],
  },
  {
    id: "lex.quitanda",
    pattern: "quitandas?",
    severity: "block",
    suggestion: "frutaria",
    category: "lexical",
    examples: ["quitanda e padaria"],
  },
  {
    id: "lex.acougue",
    pattern: "açougues?",
    severity: "block",
    suggestion: "talho",
    category: "lexical",
    examples: ["açougue e mercearia"],
  },
  {
    id: "lex.sorvete",
    pattern: "sorvetes?",
    severity: "block",
    suggestion: "gelado",
    category: "lexical",
    examples: ["um sorvete na praia"],
  },
  {
    id: "lex.suco",
    pattern: "sucos?",
    severity: "block",
    suggestion: "sumo",
    category: "lexical",
    examples: ["suco natural"],
  },
  {
    id: "lex.cafe_da_manha",
    pattern: "café\\s+da\\s+manhã",
    severity: "block",
    suggestion: "pequeno-almoço",
    category: "lexical",
    examples: ["café da manhã na varanda"],
  },
  {
    id: "lex.geladeira",
    pattern: "geladeiras?",
    severity: "block",
    suggestion: "frigorífico",
    category: "lexical",
    examples: ["cozinha com geladeira"],
  },
  {
    id: "lex.freezer",
    pattern: "freezers?",
    severity: "warn",
    suggestion: "congelador / arca congeladora",
    category: "lexical",
    examples: ["geladeira com freezer"],
  },
  {
    id: "lex.lava_loucas",
    pattern: "lava-?louças?",
    severity: "warn",
    suggestion: "máquina de lavar loiça",
    category: "lexical",
    examples: ["cozinha com lava-louças"],
  },
  {
    id: "lex.coifa",
    pattern: "coifas?",
    severity: "block",
    suggestion: "exaustor",
    category: "lexical",
    examples: ["fogão com coifa"],
  },
  {
    id: "lex.cooktop",
    pattern: "cooktops?",
    severity: "block",
    suggestion: "placa de indução / placa vitrocerâmica",
    category: "lexical",
    examples: ["cooktop de indução"],
  },
  {
    id: "lex.mofo",
    pattern: "mofos?",
    severity: "block",
    suggestion: "bolor",
    category: "lexical",
    examples: ["sem mofo"],
  },
  {
    id: "lex.vazamento",
    pattern: "vazamentos?",
    severity: "block",
    suggestion: "fuga (de água)",
    category: "lexical",
    examples: ["sem vazamentos"],
  },
  {
    id: "lex.gramado",
    pattern: "gramados?",
    severity: "block",
    suggestion: "relvado",
    category: "lexical",
    examples: ["gramado bem cuidado"],
  },
  {
    id: "lex.grama",
    pattern: "(?<!\\d\\s*)gramas?",
    severity: "warn",
    suggestion: "relva",
    category: "lexical",
    note: "«grama» after a digit is a unit of weight and is not flagged.",
    examples: ["jardim com grama"],
  },
  {
    id: "lex.frente_mar",
    pattern: "frente\\s+mar",
    severity: "warn",
    suggestion: "frente ao mar / primeira linha de mar",
    category: "lexical",
    examples: ["apartamento frente mar"],
  },
  {
    id: "lex.pe_na_areia",
    pattern: "pé\\s+na\\s+areia",
    severity: "warn",
    suggestion: "junto à praia",
    category: "lexical",
    examples: ["casa pé na areia"],
  },
  {
    id: "lex.vista_livre",
    pattern: "vista\\s+livre",
    severity: "warn",
    suggestion: "vista desafogada",
    category: "lexical",
    examples: ["vista livre para o parque"],
  },
  {
    id: "lex.ensolarado",
    pattern: "ensolarad[oa]s?",
    severity: "block",
    suggestion: "luminoso / soalheiro",
    category: "lexical",
    examples: ["sala ampla e ensolarada"],
  },
  {
    id: "lex.aconchegante",
    pattern: "aconchegantes?|aconchego",
    severity: "warn",
    suggestion: "acolhedor",
    category: "lexical",
    examples: ["ambiente aconchegante"],
  },
  {
    id: "lex.gostoso",
    pattern: "gostos[oa]s?",
    severity: "block",
    suggestion: "agradável",
    category: "register",
    examples: ["um espaço gostoso para receber"],
  },
  // ---- people and everyday vocabulary ----------------------------------------------------
  {
    id: "lex.usuario",
    pattern: "usuári[oa]s?",
    severity: "block",
    suggestion: "utilizador",
    category: "lexical",
    examples: ["usuários do condomínio"],
  },
  {
    id: "lex.cadastro",
    pattern: "cadastr(?:e-se|amentos?|ad[oa]s?|ar|e)",
    severity: "block",
    suggestion: "registo / registar / registe-se",
    category: "lexical",
    examples: ["cadastre-se para receber", "cadastrado no sistema"],
  },
  {
    id: "lex.cadastro_noun",
    pattern: "cadastros?",
    severity: "warn",
    suggestion: "registo",
    category: "lexical",
    note: "«cadastro predial» is a legitimate pt-PT land-registry term.",
    examples: ["faça seu cadastro"],
  },
  {
    id: "lex.gerenciar",
    pattern: `gerenci${L}*`,
    severity: "block",
    suggestion: "gerir / gestão",
    category: "lexical",
    examples: ["gerenciamento do condomínio", "gerenciado por empresa"],
  },
  {
    id: "lex.equipe",
    pattern: "(?:noss[oa]|a|uma|da|na|pela)\\s+equipes?|equipes?\\s+(?:de|comercial|especializada|técnica)",
    severity: "block",
    suggestion: "equipa",
    category: "spelling",
    examples: ["nossa equipe de vendas"],
  },
  {
    id: "lex.time",
    pattern: "(?:noss[oa]|o|um|do|no|ao)\\s+times?",
    severity: "warn",
    suggestion: "equipa",
    category: "lexical",
    examples: ["nosso time de consultores"],
  },
  {
    id: "lex.esporte",
    pattern: `esport${L}*`,
    severity: "block",
    suggestion: "desporto / desportivo",
    category: "spelling",
    examples: ["prática de esportes", "clube esportivo"],
  },
  {
    id: "lex.aposentado",
    pattern: "aposentad[oa]s?|aposentadorias?",
    severity: "block",
    suggestion: "reformado / reforma",
    category: "lexical",
    examples: ["ideal para aposentados"],
  },
  {
    id: "lex.bebe",
    pattern: "bebês?",
    severity: "block",
    suggestion: "bebé",
    category: "spelling",
    examples: ["quarto do bebê"],
  },
  {
    id: "lex.sobrenome",
    pattern: "sobrenomes?",
    severity: "block",
    suggestion: "apelido",
    category: "lexical",
    examples: ["nome e sobrenome"],
  },
  {
    id: "lex.xicara",
    pattern: "xícaras?",
    severity: "block",
    suggestion: "chávena",
    category: "lexical",
    examples: ["uma xícara de café na varanda"],
  },
  {
    id: "lex.conferir",
    pattern: "confira|venha\\s+conferir",
    severity: "warn",
    suggestion: "conheça / veja",
    category: "register",
    examples: ["Confira as fotos", "venha conferir"],
  },
  {
    id: "lex.imperdivel",
    pattern: "imperdíve(?:l|is)",
    severity: "warn",
    suggestion: "a não perder",
    category: "register",
    examples: ["oportunidade imperdível"],
  },
];

const REGISTER: Marker[] = [
  {
    id: "reg.legal",
    pattern: "(?:muito|super|bem|tão|mais)\\s+legal|legal\\s+demais|legal(?=\\s*!)",
    severity: "warn",
    suggestion: "ótimo / excelente",
    category: "register",
    note: "Only the colloquial adjective; «situação legal» (lawful) is untouched.",
    examples: ["um bairro muito legal", "O apartamento é legal!"],
  },
  {
    id: "reg.bacana",
    pattern: "bacanas?",
    severity: "block",
    suggestion: "ótimo / excelente",
    category: "register",
    examples: ["um lugar bacana"],
  },
  {
    id: "reg.ta",
    pattern: "tá",
    severity: "block",
    suggestion: "está / estão",
    category: "register",
    examples: ["tá pronto para morar"],
  },
  {
    id: "reg.ne",
    pattern: "né",
    severity: "block",
    suggestion: "não é",
    category: "register",
    examples: ["perfeito, né?"],
  },
  {
    id: "reg.demais",
    pattern: "(?:bom|boa|lind[oa]|grande|gostos[oa])\\s+demais",
    severity: "warn",
    suggestion: "muito bom / muito bonito",
    category: "register",
    examples: ["vista linda demais"],
  },
];

const SPELLING: Marker[] = [
  {
    id: "sp.economico",
    pattern: `econômic${L}*`,
    severity: "block",
    suggestion: "económico",
    category: "spelling",
    examples: ["opção econômica"],
  },
  {
    id: "sp.genero",
    pattern: "gêneros?",
    severity: "block",
    suggestion: "género",
    category: "spelling",
    examples: ["gênero de imóvel raro"],
  },
  {
    id: "sp.quilometro",
    pattern: "quilômetros?",
    severity: "block",
    suggestion: "quilómetro",
    category: "spelling",
    examples: ["a 2 quilômetros da praia"],
  },
  {
    id: "sp.bonus",
    pattern: "bônus",
    severity: "block",
    suggestion: "bónus",
    category: "spelling",
    examples: ["bônus na entrada"],
  },
  {
    id: "sp.premio",
    pattern: "prêmios?",
    severity: "block",
    suggestion: "prémio",
    category: "spelling",
    examples: ["prêmio de arquitetura"],
  },
  {
    id: "sp.comodo",
    pattern: "cômod(?:a|as|amente|idade|idades)",
    severity: "block",
    suggestion: "cómodo / comodidade",
    category: "spelling",
    examples: ["casa cômoda", "cômoda distribuição"],
  },
  {
    id: "sp.fenomeno",
    pattern: "fenômenos?",
    severity: "block",
    suggestion: "fenómeno",
    category: "spelling",
    examples: ["fenômeno de valorização"],
  },
  {
    id: "sp.academico",
    pattern: `acadêmic${L}*`,
    severity: "block",
    suggestion: "académico",
    category: "spelling",
    examples: ["comunidade acadêmica"],
  },
  {
    id: "sp.tenis",
    pattern: "tênis",
    severity: "block",
    suggestion: "ténis",
    category: "spelling",
    examples: ["quadra de tênis"],
  },
  {
    id: "sp.antonio",
    pattern: "Antônio",
    severity: "block",
    suggestion: "António",
    category: "spelling",
    examples: ["Rua Santo Antônio"],
  },
  {
    id: "sp.senior",
    pattern: "sêniors?|sêniores",
    severity: "block",
    suggestion: "sénior",
    category: "spelling",
    examples: ["residencial sênior"],
  },
  {
    id: "sp.condomino",
    pattern: `condômin${L}*`,
    severity: "block",
    suggestion: "condómino",
    category: "spelling",
    examples: ["assembleia de condôminos"],
  },
  {
    id: "sp.anonimo",
    pattern: `anônim${L}*`,
    severity: "block",
    suggestion: "anónimo",
    category: "spelling",
    examples: ["sociedade anônima"],
  },
  {
    id: "sp.onix",
    pattern: "ônix",
    severity: "block",
    suggestion: "ónix",
    category: "spelling",
    examples: ["bancada em ônix"],
  },
  {
    id: "sp.contato",
    pattern: `contat${L}*`,
    severity: "block",
    suggestion: "contacto / contactar",
    category: "spelling",
    examples: ["entre em contato", "contate-nos"],
  },
  {
    id: "sp.registro",
    pattern: `registr${L}*`,
    severity: "block",
    suggestion: "registo / registar / registado",
    category: "spelling",
    examples: ["registro atualizado", "imóvel registrado"],
  },
  {
    id: "sp.recepcao",
    pattern: `recepç${L}*|recepcion${L}*`,
    severity: "block",
    suggestion: "receção / rececionista",
    category: "spelling",
    examples: ["recepção 24 horas", "recepcionista"],
  },
  {
    id: "sp.aspecto",
    pattern: "aspectos?",
    severity: "block",
    suggestion: "aspeto",
    category: "spelling",
    examples: ["aspecto moderno"],
  },
  {
    id: "sp.perspectiva",
    pattern: "perspectivas?",
    severity: "block",
    suggestion: "perspetiva",
    category: "spelling",
    examples: ["perspectiva de valorização"],
  },
  {
    id: "sp.secao",
    pattern: "seç(?:ão|ões)",
    severity: "block",
    suggestion: "secção",
    category: "spelling",
    examples: ["seção de lazer"],
  },
  {
    id: "sp.detectar",
    pattern: `detect${L}*`,
    severity: "block",
    suggestion: "detetar / detetor",
    category: "spelling",
    examples: ["detector de fumaça", "detectado"],
  },
  {
    id: "sp.de_fato",
    pattern: "de\\s+fato",
    severity: "block",
    suggestion: "de facto",
    category: "spelling",
    note: "Bare «fato» is a suit in pt-PT and is never flagged.",
    examples: ["é de fato um bom negócio"],
  },
  {
    id: "sp.eletronico",
    pattern: `eletrônic${L}*`,
    severity: "block",
    suggestion: "eletrónico",
    category: "spelling",
    examples: ["fechadura eletrônica", "porteiro eletrônico"],
  },
  {
    id: "sp.planejamento",
    pattern: "planej(?:amento|amentos|ar|a|am|e|em|ou)",
    severity: "block",
    suggestion: "planeamento / planear",
    category: "spelling",
    examples: ["planejamento urbano", "planeje a mudança"],
  },
  {
    id: "sp.quatorze",
    pattern: "quatorze",
    severity: "block",
    suggestion: "catorze",
    category: "spelling",
    examples: ["quatorze andares"],
  },
  {
    id: "sp.dezesseis",
    pattern: "dezesseis",
    severity: "block",
    suggestion: "dezasseis",
    category: "spelling",
    examples: ["dezesseis apartamentos"],
  },
  {
    id: "sp.dezessete",
    pattern: "dezessete",
    severity: "block",
    suggestion: "dezassete",
    category: "spelling",
    examples: ["dezessete andares"],
  },
  {
    id: "sp.dezenove",
    pattern: "dezenove",
    severity: "block",
    suggestion: "dezanove",
    category: "spelling",
    examples: ["dezenove metros"],
  },
  {
    id: "sp.voo",
    pattern: "vôos?",
    severity: "block",
    suggestion: "voo",
    category: "spelling",
    examples: ["vôo direto para Lisboa"],
  },
  {
    id: "sp.trema",
    pattern: `${L}*ü${L}*`,
    severity: "block",
    suggestion: "sem trema (tranquilo, frequente)",
    category: "spelling",
    examples: ["bairro tranqüilo", "freqüente"],
  },
  {
    id: "sp.umido",
    pattern: "úmid[oa]s?|umidade",
    severity: "block",
    suggestion: "húmido / humidade",
    category: "spelling",
    examples: ["sem umidade", "parede úmida"],
  },
  {
    id: "sp.ideia",
    pattern: "idéias?",
    severity: "block",
    suggestion: "ideia",
    category: "spelling",
    examples: ["boa idéia"],
  },
  {
    id: "sp.assembleia",
    pattern: "assembléias?",
    severity: "block",
    suggestion: "assembleia",
    category: "spelling",
    examples: ["assembléia de condomínio"],
  },
  {
    id: "sp.optica",
    pattern: `óptic${L}*`,
    severity: "block",
    suggestion: "ótica",
    category: "spelling",
    examples: ["fibra óptica"],
  },
  {
    id: "sp.conosco",
    pattern: "conosco",
    severity: "block",
    suggestion: "connosco",
    category: "spelling",
    examples: ["fale conosco"],
  },
];

const GRAMMAR: Marker[] = GRAMMAR_RULES.map((r) => ({
  id: r.id,
  pattern: r.pattern,
  severity: r.severity,
  suggestion: r.suggestion,
  category: r.category,
  note: r.note,
  examples: r.examples,
}));

export const MARKERS: Marker[] = [...LEXICAL, ...REGISTER, ...SPELLING, ...GRAMMAR];

export const MARKER_BY_ID: ReadonlyMap<string, Marker> = new Map(MARKERS.map((m) => [m.id, m]));
